- .gitignore
- requirements-dev.lock
- requirements.lock
Added `.envrc` into gitignore to ignore configuration files for direnv.
Additionally, the requirements lock file from `rye sync` is updated.
> .gitignore update

- src/pnpq/devices/waveplate_stub.py
Adds types hint `None` to return type of `__init__` for stub wave plate as mentioned in #33
> Return type hint in stub waveplate's initializer

- src/pnpq/devices/odl_ozoptics_650ml.py
The bugs #34 and #35 are related. `current_step` is intended to perform the same functionality as `get_step`. Therefore, these two methods have been unified under `get_step`. Basic error handling for the UNKNOWN state has been implemented.
> Fix bugs #34 #35 for unifying and error handling of get_step in OzOptics ODL 

- .github/workflows/check.yml
- .gitignore
- .vscode/settings.json
- README.md
- bin/check.bash
- bin/install-dependencies.bash
- bin/install-rye.bash
- pyproject.toml
- requirements-dev.lock
- requirements.lock
- tests/switch_stub_test.py
- tests/waveplate_stub_test.py
Implementation for #31 
The check scripts pretty much works, but many parts of the Github worker and the install dependency scripts are pretty much experimental, and maybe will see some feedbacks regarding their structures. But everything should work at this point (and is tested in a test environment). 
Small known issues and remarks:
The `rye` version check has to be disabled temporarily because it fails for some reason in the Github worker, but actually running `rye sync` do work. I'll leave this to be fixed after the first round of feedback. 
I also replaced the `curl` to `wget` in the `install-rye` script because many systems I've been testing come with archaic version of `curl` which doesn't support the `--output-dir` functionality. 
Finally, instead of installing `shellcheck` and …
> Standardized Check Scripts and Workers for PnPQ

- .github/workflows/check.yml
- example.py
- src/pnpq/__init__.py
- src/pnpq/devices/__init__.py
- src/pnpq/devices/odl_ozoptics_650ml.py
- src/pnpq/devices/odl_thorlabs_kbd101.py
- src/pnpq/devices/optical_delay_line.py
- src/pnpq/devices/switch_stub.py
- src/pnpq/devices/switch_thorlabs_osw1310E.py
- src/pnpq/devices/utils.py
- src/pnpq/devices/waveplate_stub.py
- src/pnpq/devices/waveplate_thorlabs_kb10crm.py
- src/pnpq/devices/waveplate_thorlabs_kb10crm_test.py
- src/pnpq/utils.py
- tests/switch_stub_test.py
- tests/waveplate_stub_test.py
This fixes all formatting and static analysis errors found by the current `check.bash` script.
In the future, any PR that introduces a new error will fail. Errors will need to be corrected before merging.
> Fix static analysis errors and enable PR checks

- hardware_tests/test_polarization_controller_thorlabs_mpc320.py
- src/pnpq/devices/polarization_controller_thorlabs_mpc320.py
- src/pnpq/units.py
Closes #57 
I didn't test this code on real hardware since I didn't have access to one from writing this software. It would be nice if @auspicacious can try it (or I can try it on Friday). 
I implemented pint for `move_absolute` function (in parameter) as well as the `home_position` of the `PolarizationControllerParams` struct.
> Add pint to MPC320

- src/pnpq/apt/protocol.py
- tests/apt/test_protocol.py
As @TomShen1234 pointed out, the `.check()` function returns a boolean and does not throw an exception, meaning that the existing code was not working as expected.
I attempted to use Pint's `check` decorator by redefining `motor_current` as a `@property` and creating a decorated setter function, but Python's property decorators do not seem to co-exist well with dataclasses, mypy, ruff, or pylint.
> Ensure that motor_current is actually a quantity of type current.

- hardware_tests/test_polarization_controller_thorlabs_mpc320.py
- src/pnpq/apt/connection.py
- src/pnpq/devices/polarization_controller_thorlabs_mpc320.py
I'd say this closes #29 
A new `AptConnection` class was added, with the codes itself roughly unchanged from its initial implementation in the MPC320 class. 
To use the new class, initialize the connection object first, then pass it into the device class:
```
connection = AptConnection(serial_number="12345678")
return PolarizationControllerThorlabsMPC320(connection=connection)
```
> Refactor serial communication code into a new class

- src/pnpq/apt/protocol.py
- tests/apt/test_protocol.py
Partial implementation of #56 
Attempted to implement 3 more messages: MOVE_JOG, MOVE_STOP, MOVE_STOPPED
Created 2 new enums in the process: StopMode and JogDirection.
MOVE_JOG and MOVE_STOP use very similar code, so I am wondering if there's a better way to do this.
Also, while I have implemented the first 6 bytes of MSMSG_MOT_MOVE_STOPPED, the entire message is supposed to be 20 bytes. However, a similar message (MGMSG_MOT_MOVE_COMPLETED) is also in a similar format, but in reality the MPC320  does not follow up with the extra 14 bytes. So I have left it unfinished for now.
> add 3 more messages: MOVE_JOG, MOVE_STOP, MOVE_STOPPED

- src/pnpq/apt/connection.py
- src/pnpq/devices/polarization_controller_thorlabs_mpc320.py
One-line code change with a lot of explanatory comments.
@TomShen1234 @master-of-ppap I think that we should merge this PR, then, after @master-of-ppap finishes writing the driver implementation for `jog` in a separate PR, we should re-test on the hardware.
I am a little concerned that this will add 0.4 seconds to every move command. We might be able to tune this downward a little. But we have to disable the channel after each move if we want to use the device accurately, since otherwise it will just sit there vibrating, and that means having some kind of short delay.
> Add sleep after sending no-reply commands.

- hardware_tests/test_polarization_controller_thorlabs_mpc320.py
- src/pnpq/devices/polarization_controller_thorlabs_mpc320.py
Closes #68 
I have yet to test this code on the real device. It would be nice if I can have some support on that. 
I removed the `dataclass` decorator on `PolarizationControllerParams`, and changed it into a `TypedDict`. The class property is also removed in favor of `refresh_params` returning the dictionary. 
The only change is that the parameter now have to be used with the dictionary syntax rather than a class (which requires some string accessed variables). Let's discuss whether this is ideal. 
The interface for `set_params` remains unchanged, with the underlying logic changed to fetch the current params, update the dictionary, and sending the updated dictionary back to the device.
> Changed MPC320 parameters to TypedDict

- hardware_tests/test_polarization_controller_thorlabs_mpc320.py
- sphinx/source/conf.py
- src/pnpq/apt/protocol.py
- src/pnpq/devices/polarization_controller_thorlabs_mpc320.py
- src/pnpq/units.py
- tests/apt/test_protocol.py
- tests/test_pint_units.py
Closes #76 hopefully.
*  Updated the rest of the parameters of the `PolarizationControllerParams` class (velocity, jog_step_1 2 and 3) to make use of pint's `Quantity` class.
* Updated the test driver code to reflect these new unit updates.
* Implemented a new dimensionless `mpc320_velocity` unit for the `PolarizationControllerParams` velocity field. 
* In the APT Communications Protocol, it states that the velocity value is a dimensionless percentage value from 10% to 100%, which reflects the proportion of its max speed (400 degrees/sec) to its velocity. In order to support non-dimensionless units (such as degree/second), I have also added a unit transformation tool using pint's `Context` function.
* Side note: 400 degree/second seems extremely quick, maybe the protocol actually meant …
> Support pint's Quantity for other PolarizationControllerParams fields

- tests/test_mock.py
- tests/test_polarization_controller_thorlabs_mpc320.py
Closes #74. In theory.
Additions: 
* Created a new test file called `test_mock.py` (is this a good file name?). 
* Uses the `Mock` object from the `unittest` library to mock the behavior of the `AptConnection` class.
* Supports only the `move_absolute` function of the `PolarizationControllerThorlabsMPC320` at the moment.
* Uses the sideeffect functionality to simulate the driver accepting a message, and returning a hypothetical reply. The unit test then checks if whether or not the driver correctly recognizes this hypothetical reply. 
* Asserts that the `AptConnection.send_message_expect_reply()` was correctly called three times. (Two for enabling and disabling the channel, one for the movement itself)
Considerations:
* I would like to assert if the `AptMessage_MGMSG_MOT_MOVE_ABSOLUTE` …
> Mock controller to test mpc320's move_absolute()

- src/pnpq/apt/protocol.py
- src/pnpq/devices/polarization_controller_thorlabs_mpc.py
- tests/apt/test_protocol.py
I have been pulling my hair out on trying to find an elegant way of separating the dataclasses, and I think I found an alright solution.
Additions:
* Added two new classes `AptMessage_MGMSG_MOT_MOVE_COMPLETED_6_BYTES` and `AptMessage_MGMSG_MOT_MOVE_COMPLETED_20_BYTES` that inherit from a main `AptMessage_MGMSG_MOT_MOVE_COMPLETED` class. These reflect the two different possibilities of `MOVE_COMPLETED`  messages for the Thorlabs devices. One type contains only 6 header bytes, while the other type contains 6 bytes with an additional 14 data bytes. This can be seen on p.125 of the APT Communications Protocol.
* Added their respective unit tests. 
* Updated the existing MPC320 driver to use this new dataclass.
Considerations:
* As far as we know, the MPC320 prefers the 6 byte message, while …
> Split MOVE_COMPLETED into two separate dataclasses for 6-byte and 20-byte messages.

- hardware_tests/test_polarization_controller_thorlabs_mpc320.py
- src/pnpq/devices/polarization_controller_thorlabs_mpc.py
Closes #95 
Implements 2 functions:
- `get_status(self, chan_ident: ChanIdent) -> AptMessage_MGMSG_MOT_GET_USTATUSUPDATE` - Get status for a specified channel
- `get_status_all(self) -> list[AptMessage_MGMSG_MOT_GET_USTATUSUPDATE]` - Get a list of status for all channels
> Adds get_status

- src/pnpq/apt/protocol.py
- tests/apt/test_protocol.py
This function would come in handy in implementing external libraries where int has to be passed to the initializer of the `ChanIdent` enum. 
In addition, a test was also added: `test_ChanIdent_init`
> Add an initializer to ChanIdent to support initialization from integers

- src/pnpq/units.py
- tests/test_pint_units.py
While messing around with testbed-node last week with Tom, we encountered a strange error in which radians converted to type `mpc320_step` visually resulted in the wrong angle on the device. I was looking through the `units.py` code and found the culprit of this issue.
When converting specific angles into `mpc320_step`, we perform the conversion based on the assumption that the input angle is in degrees. However, this may not necessarily be the case. 
Therefore, an easy fix is to convert the inputted angle into degrees first, then perform the conversion calculation to `mpc320_step`.
I have implemented this quick fix and also updated the unit tests to accordingly test for conversions from non-degree type angles (such as radians).
> Fix bug that made non-degree type angles be incorrectly converted to mpc320_step 

- src/pnpq/units.py
- tests/test_pint_units.py
Closes #103 
This should have been split into two different pull requests but I worked on them on the same branch, and I'm not sure if it's possible to split it now... So, I'll leave it like this for now. Please forgive me.
* Adds a mock waveplate for the K10CR1 that verifies the `move_absolute` method in the base driver listens for the appropriate message
* Since the `units.py` class was getting a bit repetitive, I tried to encapsulate the repeated code into a function `get_unit_transformation` which generates the appropriate transformation units. 
* Also has flexibility to allow for complex transformations using a lambda function, as well as the ability to round the output or limit the output to a certain range.
> Add K10CR1 mock waveplate and refactor pint units code to use generator

- tests/test_polarization_controller_thorlabs_mpc320.py
Closes #102.
Hello. Okinawa Coder here. I love listening to talks. 
* Implements new mock methods to ensure we are expecting the correct message replies in the MPC320 driver.
* test_jog(), test_invalid_angle_inputs(), test_set_params(), test_get_params() and test_get_status().
* Did not implement test_connection() because it didn't make much sense. Because it's not a part of the driver.
> Add more functionality to mock mpc320

- src/pnpq/devices/refactored_waveplate_thorlabs_k10cr1.py
- src/pnpq/devices/refactored_waveplate_thorlabs_k10cr1_stub.py
- tests/test_polarization_controller_thorlabs_mpc320_stub.py
- tests/test_refactored_thorlabs_k10cr1_stub.py
Closes #114 
* Added ABC implementation for K10CR1 waveplate
* Created a new refactored stub K10CR1 waveplate to incorporate the refactored K10CR1 waveplate class.
* (Yes, I was told to refactor the old one, but after looking at the code, I thought it would be easier just to restart from scratch. It's really short anyway
* This stub waveplate is super bare bones. It's going to fall apart any moment. But it should be good for now.
* Created respective tests for the new stub K10CR1 waveplate.
* Fixed small typo in MPC stub tests.
> Implemented ABC for Thorlabs K10CR1 waveplate, stub device with tests

- src/pnpq/units.py
- tests/test_pint_units.py
Working towards closing #104.
Hello. 11 PM coder here.
In order to add more functionality to the K10CR1 driver code, we need to implement messages such as `MGMSG_MOT_SET_VELPARAMS` and `MGMSG_MOT_GET_VELPARAMS`. However, these messages utilize new types of units: velocities and accelerations. This is what I worked on here.
* Added custom `k10cr1_velocity` and `k10cr1_acceleration` pint units.
* Added appropriate conversions to and from `degrees / second` and `degrees / second ** 2`.
* Added appropriate conversions to and from `k10cr1_step`as well (because `k10cr1_step` has its own dimension).
*  One caveat is that we cannot convert between `mpc320_step` and `k10cr1_step` because of our custom dimensionality implementation, but that shouldn't be an issue.
* Added corresponding unit tests. …
> Velocity and acceleration pint units for K10CR1

- hardware_tests/test_thorlabs_k10cr1.py
- src/pnpq/apt/protocol.py
- src/pnpq/devices/polarization_controller_thorlabs_mpc.py
- src/pnpq/devices/refactored_waveplate_thorlabs_k10cr1.py
- src/pnpq/devices/refactored_waveplate_thorlabs_k10cr1_stub.py
- tests/apt/test_protocol.py
- tests/test_refactored_thorlabs_k10cr1_stub.py
Helps in closing #104
* Added `get_velparams` and `set_velparams` to `WaveplateThorlabsK10CR1` driver.
* Added three new messages `MGMSG_MOT_SET_VELPARAMS`, `MGMSG_MOT_REQ_VELPARAMS` and `MGMSG_MOT_GET_VELPARAMS`. 
* Also added the corresponding unit tests.
* Also updated the stub K10CR1 device as well.
* Added a `current_velocity_params` to save the current parameters on the stub device.
* Updated the protocol to have the message store data in a `Quantity` instead of `int` so users can easily change units.
> Add velparams functions to K10CR1 waveplate driver, stub and tests

- src/pnpq/apt/protocol.py
- tests/apt/test_protocol.py
One step closer to closing #104.
* Added six new APT messages:
* `MGMSG_MOT_SET_JOGPARAMS`
* `MGMSG_MOT_REQ_JOGPARAMS`
* `MGMSG_MOT_GET_JOGPARAMS`
* `MGMSG_MOT_SET_HOMEPARAMS`
* `MGMSG_MOT_REQ_HOMEPARAMS`
* `MGMSG_MOT_GET_HOMEPARAMS`
* Added a few new enums that the messages use.
* Also added their corresponding unit tests
* Also added a unit test that was not added for `AptMessage_MGMSG_MOT_REQ_VELPARAMS`. My bad. Forgot to add that.
> Add more APT messages!

- src/pnpq/devices/refactored_odl_thorlabs_kbd101.py
- src/pnpq/devices/refactored_odl_thorlabs_kbd101_stub.py
- tests/test_refactored_thorlabs_kbd101_stub.py
Close #133 
Close #43 
This PR implemented a bit more than what's described in the original issue. 
- Added the following functions:
- `jog`
- `get_homeparams`
- `set_homeparams`
- `get_jogparams`
- `set_jogparams`
- `get_status`
- Updated stub device and unit tests (unit test now covers 100% of the stub device's code)
- Fixed some mistakes in documentation from the last PR (#126)
Now, the new ThorLabs ODL driver should be in feature parity with the old one (and even surpassed it in some areas). After this PR and #104 is finished, we can consider removing the old drivers (#121).
Another small thing to consider: the parameters class (`OpticalDelayLineVelocityParams`, etc.) are identical to the waveplate counterpart due to them using the same messages. Maybe we should consider merging them? …
> Add more functions to refactored ODL

- src/pnpq/apt/connection.py
- src/pnpq/devices/refactored_odl_thorlabs_kbd101.py
- src/pnpq/devices/refactored_odl_thorlabs_kbd101_stub.py
- src/pnpq/devices/refactored_waveplate_thorlabs_k10cr1.py
- src/pnpq/devices/refactored_waveplate_thorlabs_k10cr1_stub.py
While doing another PR it occurred to me that it would be better if we avoided using class variables as much as possible, to prevent confusion.
I haven't touched the ones related to channel configuration, because I think that might interfere with some of the work you're doing. I did remove some unused variables. I think it might be a good idea to make the channel variables into instance variables, though.
I haven't touched anything in the protocol classes, since those are not plausibly reconfigurable and I doubt anyone will ever try to change those values.
> Clean up some class variables

- hardware_tests/test_thorlabs_k10cr1.py
- src/pnpq/devices/refactored_waveplate_thorlabs_k10cr1.py
- src/pnpq/devices/refactored_waveplate_thorlabs_k10cr1_stub.py
- src/pnpq/devices/waveplate_thorlabs_kb10crm.py
- src/pnpq/devices/waveplatetest.py
- tests/test_refactored_thorlabs_k10cr1_stub.py
- tests/test_waveplate_thorlabs_k10cr1.py
Assists in closing #104
* Support many methods for K10CR1 waveplate driver
* `move_absolute`
* `get_velparams`
* `set_velparams`
* `get_jogparams`
* `set_jogparams`
* `get_homeparams`
* `set_homeparams`
* `jog`
* `home`
* `identify`
* `is_homed`
* Tested against real device. Also added a feature to automatically home the device if not already homed, to ensure consistency.
* Mock driver not fully implemented, however... I want to check if what I'm doing is correct before going to the mock driver!
> Implement many functions for K10CR1 waveplate

- README.md
Closes https://github.com/moonshot-nagayama-pj/PnPQ/issues/153 for real this time.
After testing, it appears that GitHub's automatic citation generation does not include DOI; updating the text to make this clear and show how to find it.
> Update citing information

- src/pnpq/devices/waveplate_thorlabs_k10cr1.py
Closes https://github.com/moonshot-nagayama-pj/PnPQ/issues/142
Needs testing on real hardware before merge.
Set k10cr1 configuration parameters to the same values observed in the official software, for set commands that we support.
> Initialize K10CR1 with approriate home parameters on startup

- src/pnpq/apt/connection.py
Changed the return type of `_find_port` to superclass (`serial.tools.list_ports_common.ListPortInfo`) so that mypy checks pass on macOS.
> Fix mypy error with serial library on macOS
